spring:
  profiles:
    include: local, production
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    org.springframework.web.client: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security: debug
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true