spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update #update create-update validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    database: mysql
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://rdsinstance.cg6o3rqphy1s.ap-northeast-2.rds.amazonaws.com:3306/rdsDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: sidsidvjscl12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: myPass
  mail:
    host: smtp.gmail.com
    username: dev.eunchan@gmail.com
    password: zhvswatyvhvluwhe
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fc651896d01311768df6b801a157fc66
            redirect-uri: https://momo-api.shop/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_image
              - account_email
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.springframework.web.client: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security: debug
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config: classpath:logback-spring.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secretKey: jwt-tokens-that-should-be-changed-production
  refreshKey: jwt-refresh-tokens-that-should-be-changed-production

payments:
  toss:
    successUrl: /payments/success
    failUrl: /payments/fail
    secretKey: test_sk_O6BYq7GWPVvlvv1l20n8NE5vbo1d
    clientKey: test_ck_oeqRGgYO1r5YKK0od4arQnN2Eyaz
    url: https://api.tosspayments.com/v1/payments/

banking:
  client_id: 42c29ffd-a7d7-4e02-aa66-71c49781ffb8
  client_secret: 470073e6-effd-4bb6-8adb-45180e3716c8
  tran_id: M202300084